#!/usr/bin/env bash
set -euo pipefail

# entrypoint: ensure X/WSLg environment is available for both container startup
# and for later `docker exec -it ... bash` shells (writes /etc/profile.d/99-x11.sh
# and ensures ~/.bashrc sources it).

PROFILE_SNIPPET=/etc/profile.d/99-x11.sh

# write a portable, idempotent profile snippet
cat > "$PROFILE_SNIPPET" <<'EOF'
# X11 / WSLg helper (generated by entrypoint)
: "${DISPLAY:=}"
export DISPLAY
: "${XDG_RUNTIME_DIR:=/tmp/runtime-root}"
export XDG_RUNTIME_DIR
: "${QT_X11_NO_MITSHM:=1}"
export QT_X11_NO_MITSHM

# Export XAUTHORITY only if the file actually exists inside the container
if [ -n "${XAUTHORITY-}" ] && [ -f "${XAUTHORITY}" ]; then
  export XAUTHORITY
else
  unset XAUTHORITY
fi
EOF

chmod 644 "$PROFILE_SNIPPET" || true

# ensure interactive shells load the profile snippet
if ! grep -qF 'source /etc/profile.d/99-x11.sh' /root/.bashrc 2>/dev/null; then
  cat >> /root/.bashrc <<'BASHRC'

# ensure X11/WSLg environment is exported for interactive shells
if [ -f /etc/profile.d/99-x11.sh ]; then
  source /etc/profile.d/99-x11.sh
fi
BASHRC
fi

# If XAUTHORITY was provided but the file isn't present, warn and unset it
if [ -n "${XAUTHORITY-}" ] && [ ! -f "${XAUTHORITY}" ]; then
  echo "[entrypoint] Warning: XAUTHORITY='${XAUTHORITY}' set but file not found in container; ignoring XAUTHORITY" >&2
  unset XAUTHORITY || true
fi

# Detect WSL/WSLg and avoid trying to use XAUTHORITY there
if grep -qi microsoft /proc/version 2>/dev/null; then
  # WSL/WSLg typically does not require XAUTHORITY cookie files
  unset XAUTHORITY || true
fi

# If the first arg looks like an option, run bash with it
if [ "${1-}" = "" ] || [ "${1:0:1}" = "-" ]; then
  set -- bash "$@"
fi

exec "$@"
